# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# DISABLE ALL DEFAULT DEPENDABOT STUFF
# We are using renovate instead.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    ignore:
      - dependency-name: "*"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/"
    ignore:
      - dependency-name: "*"
    schedule:
      interval: daily
  - package-ecosystem: uv
    directory: "/"
    ignore:
      - dependency-name: "*"
    schedule:
      interval: daily
